### ISSUE TITLE
DataFrame object has no attribute append

### ISSUE THREAD

**Issue by karla-desouza** [dreji18/Bio-Epidemiology-NER#8]
When I try to run the example using the Python package, I get the following error: 
> `AttributeError:` 'DataFrame' object has no attribute 'append'

I think it is caused because `append` was removed from pandas and now we need to use `concat` instead.

**Comment by dreji18** [comment]
Hi Karla, thanks for bringing this, Could you let me know the pandas version you are using, 

also could you please check with pandas==1.5.3

**Comment by ghost** [comment]
Hi Deepak, I'm using pandas==2.0.0. The example works perfectly with pandas==1.5.3. Thanks!

**Comment by dreji18** [comment]
Thanks, Karla, I will update the code based on it, lemme know if you would like to contribute :)

**Comment by ghost** [comment]
I'd love to. Please let me know how I can contribute!

**Comment by dreji18** [comment]
Thanks Karla-I will post the code block in this repo, you can create a pull request and update the code for this issue.

**Comment by ghost** [comment]
Hi @dreji18! Can you share the source code so that I can help fix this issue?

**Comment by dreji18** [comment]
Hi @karla-desouza, please find the dev brach, you could do your changes and after testing let me know, I will take the build to the pypi

https://github.com/dreji18/Bio-Epidemiology-NER/tree/dev

**Comment by ghost** [comment]
Hi @dreji18 , I made the changes, but when I try to push to dev I get a permission denied message.

**Comment by dreji18** [comment]
Hi @karla-desouza , I have given the contributor access now, could you please try again.
